export const FOOD = [
    {
        id: 0,
        name: "Canidae",
        type: "Pure",
        flavor: "Salmon and Sweet Potato",
        quantity: 10,
        aisle: 1,
        bin: 1,
        date: "",
    },
    {
        id: 1,
        name: "Canidae",
        type: "Pure",
        flavor: "Lamb and Pea",
        quantity: 30,
        warehouseLocation: 3,
    },
    {
        id: 2,
        name: "Canidae",
        type: "Goodness",
        flavor: "Real Turkey and Barley",
        quantity: 20,
        warehouseLocation: 4,
    },
    {
        id: 3,
        name: "Canidae",
        type: "Sustain",
        flavor: "Planet-Friendly Cage-Free Chicken",
        quantity: 10,
        warehouseLocation: 8,
    },
    {
        id: 4,
        name: "Nulo",
        type: "Medalseries",
        flavor: "Baked and Brothy Chicken, Duck, Turkey",
        quantity: 20,
        warehouseLocation: 10,
    },
    {
        id: 5,
        name: "Nulo",
        type: "Medalseries",
        flavor: "High-Protein Chicken and Peas",
        quantity: 30,
        warehouseLocation: 11,
    },
    {
        id: 10,
        name: "Nulo",
        type: "Medalseries",
        flavor: "High-Protein Turkey, Whitefish, Quinoa",
        quantity: 10,
        warehouseLocation: 12,
    },
    {
        id: 6,
        name: "Earthborn",
        type: "Grain Free",
        flavor: "Great Plains Feast",
        quantity: 60,
        warehouseLocation: 14,
    },
    {
        id: 7,
        name: "Earthborn",
        type: "Grain Free",
        flavor: "Meadow Fest",
        quantity: 20,
        warehouseLocation: 16,
    },
    {
        id: 11,
        name: "Earthborn",
        type: "Grain Free",
        flavor: "Primitive Natural",
        quantity: 30,
        warehouseLocation: 17,
    },
    {
        id: 8,
        name: "Earthborn",
        type: "Venture",
        flavor: "Smoked Bison and Pumpkin",
        quantity: 10,
        warehouseLocation: 18,
    },
    {
        id: 9,
        name: "Earthborn",
        type: "Venture",
        flavor: "Duck Meal and Pumpkin",
        quantity: 10,
        warehouseLocation: 18,
    },
];
