export const RECIPIENTS = [
    {
        id: 0,
        name: "Lola Roskilly",
        address: "97 Crest Line Avenue",
        city: "Mountain View",
        state: "CA",
        zipcode: "95875",
        donatedQuantity: 1,
    },
    {
        id: 1,
        name: "Syd Scutcheon",
        address: "9 Morrow Lane",
        donatedQuantity: 2,
    },
    {
        id: 2,
        name: "Shadow Bullers",
        address: "56169 International Court",
        donatedQuantity: 2,
    },
    {
        id: 3,
        name: "Taddeusz Kean",
        address: "840 Comanche Place",
        donatedQuantity: 1,
    },
    {
        id: 4,
        name: "Baron Kenforth",
        address: "43319 Vidon Junction",
        donatedQuantity: 1,
    },
    {
        id: 5,
        name: "Robin Godilington",
        address: "365 Autumn Leaf Trail",
        donatedQuantity: 3,
    },
    {
        id: 6,
        name: "Lucias Filippozzi",
        address: "0 Brickson Park Center",
        donatedQuantity: 1,
    },
    {
        id: 7,
        name: "Maurene Enright",
        address: "7568 Shelley Crossing",
        donatedQuantity: 1,
    },
    {
        id: 8,
        name: "Wildon Duddin",
        address: "4 Nobel Pass",
        donatedQuantity: 2,
    },
    {
        id: 9,
        name: "Nollie Downgate",
        address: "25298 Tomscot Junction",
        donatedQuantity: 1,
    },
    {
        id: 21,
        name: "Shadow Bullers",
        address: "56169 International Court",
        donatedQuantity: 2,
    },
    {
        id: 22,
        name: "Shadow Bullers",
        address: "56169 International Court",
        donatedQuantity: 2,
    },
];
